- name: Create directory for apt keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  ansible.builtin.shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install the latest version of Docker Engine and containerd
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: true

- name: Add the admin user to the docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Install pip3
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true

- name: Install Docker Module for Python and JSONdiff
  ansible.builtin.pip:
    name:
      - docker
      - jsondiff
      - pyyaml

- name: Start and enable Docker systemd service.
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true